 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/profile_pictures", type: :request do
  # ProfilePicture. As you add validations to ProfilePicture, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProfilePicture.create! valid_attributes
      get profile_pictures_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      profile_picture = ProfilePicture.create! valid_attributes
      get profile_picture_url(profile_picture)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_profile_picture_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      profile_picture = ProfilePicture.create! valid_attributes
      get edit_profile_picture_url(profile_picture)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProfilePicture" do
        expect {
          post profile_pictures_url, params: { profile_picture: valid_attributes }
        }.to change(ProfilePicture, :count).by(1)
      end

      it "redirects to the created profile_picture" do
        post profile_pictures_url, params: { profile_picture: valid_attributes }
        expect(response).to redirect_to(profile_picture_url(ProfilePicture.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProfilePicture" do
        expect {
          post profile_pictures_url, params: { profile_picture: invalid_attributes }
        }.to change(ProfilePicture, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post profile_pictures_url, params: { profile_picture: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested profile_picture" do
        profile_picture = ProfilePicture.create! valid_attributes
        patch profile_picture_url(profile_picture), params: { profile_picture: new_attributes }
        profile_picture.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the profile_picture" do
        profile_picture = ProfilePicture.create! valid_attributes
        patch profile_picture_url(profile_picture), params: { profile_picture: new_attributes }
        profile_picture.reload
        expect(response).to redirect_to(profile_picture_url(profile_picture))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        profile_picture = ProfilePicture.create! valid_attributes
        patch profile_picture_url(profile_picture), params: { profile_picture: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested profile_picture" do
      profile_picture = ProfilePicture.create! valid_attributes
      expect {
        delete profile_picture_url(profile_picture)
      }.to change(ProfilePicture, :count).by(-1)
    end

    it "redirects to the profile_pictures list" do
      profile_picture = ProfilePicture.create! valid_attributes
      delete profile_picture_url(profile_picture)
      expect(response).to redirect_to(profile_pictures_url)
    end
  end
end
